[NOTICKET] add configurations for rabbitmq and elasticsearch. Enable configurable additional php extensions.
kellerkinderDE/devenv-shopware pull request #13
Opened 2023-02-04 10:45 UTC by jochenmanz

2023-02-06 14:57 UTC, kleinmann requested changes
Just a bit of naming polish, looks good otherwise 🙂

2023-02-06 14:57 UTC, kleinmann commented on devenv.nix
> +      description = "Additional php extensions";
```suggestion
      description = "Additional PHP extensions";
```

2023-02-06 14:57 UTC, kleinmann commented on devenv.nix
> +      description = "Enables ElasticSearch";
```suggestion
      description = "Enable Elasticsearch";
```

2023-02-06 14:57 UTC, kleinmann commented on devenv.nix
> +      description = "Enables RabbitMq";
```suggestion
      description = "Enable RabbitMQ";
```

2023-02-06 14:57 UTC, kleinmann commented on devenv.nix
> +    enableElasticSearch = lib.mkOption {
```suggestion
    enableElasticsearch = lib.mkOption {
```

2023-02-07 08:05 UTC, Zwaen91 commented
I would suggest adding the new possible configurations to the README file.

2023-02-07 12:29 UTC, jochenmanz commented on devenv.nix
> +      description = "Enables RabbitMq";
Done :)

2023-02-07 12:29 UTC, jochenmanz commented on devenv.nix
> +      description = "Enables ElasticSearch";
Done :)

2023-02-07 12:29 UTC, jochenmanz commented on devenv.nix
> +      description = "Additional php extensions";
Done :)

2023-02-07 12:31 UTC, jochenmanz commented
> I would suggest adding the new possible configurations to the README file.

Ive added more documentation to our readme.md

2023-02-07 13:58 UTC, jochenmanz commented on devenv.nix
> +    enableElasticSearch = lib.mkOption {
Done :)

2023-02-07 16:37 UTC, kleinmann approved these changes

2023-02-07 17:39 UTC, merged